### ISSUE TITLE
Bok Choy preserve bug?

### ISSUE THREAD

**Issue by KingCosmic** [VincentAmante/palia-tools#102]
when planted and telling it you'll sell seeds Bok Choy increases profit, but when you tell it you'll do preserves profits drop, I took a quick look through the data part of the code but things seemed fine. Wanted to open an issue up.

My layout incase it helps.
https://palia-garden-planner.vercel.app/?layout=v0.2_DIM-111-111-111_CROPS-TOTPAACAA-PCPAOAANA-TOTAAPAAT-PAATCOPAA-ANANNNANA-AAPCOTAAP-CAAPAATOT-ANAAOAPCP-AATAAPTOT

**Comment by VincentAmante** [comment]
Hello! thanks for bringing this up. A couple questions to ask:
- By drop in profit do you mean in relation to the seeds or to the crops?
- What are your main settings?

Since sell values looks fine, this might be caused by a weird interaction with replant mechanics and the processor

**Comment by KingCosmic** [comment]
That is the wrong layout.. idk why it pasted that code, but basically just
go and add bok choy to a layout.

https://palia-garden-planner.vercel.app/?layout=v0.2_DIM-111-111-111_CROPS-BkOBkTPTBkOBk-OBkOPTPOBkO-BkOBkTPTBkOBk-TPTBkOBkTPT-PTPOBkOPTP-TPTBkOBkTPT-BkOBkTPTBkOBk-OBkOPTPOBkO-BkOBkTPTBkOBk

Go into crop settings and change bok choy from crop to seed and you'll see
the last harvest increase and then if you change it from seed to jar you'll
see it decrease. I assumed it was because of conversion time but saw how
that's not taken into account yet. I think I also saw it happen with
another plant but can't remember off the top of my head atm

**Comment by VincentAmante** [comment]
Oh, in that case, this might not be a bug after all but just the constraints of the app. 

When conversion time isn't factored in, Bok Choy seeds win out per unit since 1 starred bok choy converts to 4 seeds that sells for 88 total, as opposed to 1 starred bok choy for 1 kimchi which sells for 67 gold instead. The total value (last harvest) is correct, it's just that the raw average is limited in that it only averages by harvest time instead of processing hours.

This explanation seems to check out when replicating your setup, but do let me know if there's something I missed

**Comment by KingCosmic** [comment]
nope totally makes sense, I was wondering why that happened on normal bok choy too but just realized I was looking at nappa cabbage selling for 60 per preserved, not the bok choy selling for 47 or whatever, Thanks!
